# Generated by Django 2.1.5 on 2019-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pysakki',
            field=models.CharField(default='Keskustori', max_length=50),
        ),
    ]
