# Generated by Django 2.1.5 on 2019-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_pysakki'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_2', models.CharField(max_length=4, unique=True)),
                ('name', models.TextField()),
            ],
        ),
    ]
