# Generated by Django 2.1.5 on 2019-03-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogi',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
