# Generated by Django 2.1.5 on 2019-03-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190326_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='id_2',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
