# Generated by Django 2.1.5 on 2019-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190328_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pysakkivalinta',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
