# Generated by Django 2.1.5 on 2019-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190329_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pysakkivalinta',
            field=models.CharField(choices=[(0, 'Pysäkki 1'), (1, 'Pysäkki 2'), (2, 'Pysäkki 3')], max_length=1),
        ),
    ]
