# Generated by Django 2.1.5 on 2019-03-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190329_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pysakkivalinta',
            field=models.IntegerField(default=0),
        ),
    ]
