# Generated by Django 2.1.5 on 2019-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190401_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linja',
            field=models.CharField(default='3', max_length=5),
        ),
    ]
