# Generated by Django 2.1.5 on 2019-04-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_linja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pysakki1',
            new_name='pysakki',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pysakki2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pysakki3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pysakkivalinta',
        ),
    ]
